databases:
  - name: badger-99
    databaseName: money_mate
    user: alfred

services:
  - type: web
    name: alfred
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alfred
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
