default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials.postgres[:username] %>
  password: <%= Rails.application.credentials.postgres[:password] %>
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: money_mate

test:
  <<: *default
  database: money_mate-testing

production:
  database: money_mate
  <<: *default